services:
  - type: web
    name: asf-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
